repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0  # you can also use latest tag from GitHub if needed
    hooks:
      - id: ruff
        args: []
      - id: ruff-format
